language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-bedrock' ]; then cd .. && eval "mv $currentfolder generator-bedrock" && cd generator-bedrock; fi
